server:
  port: 8000 
  
spring:
  application:
    name: reading-eureka
  security:
    user:
      name: root
      password: 123456
    
    
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://root:123456@${eureka.instance.hostname}:${server.port}/eureka/    

    
